Products/config/routes.rb
Rails.application.routes.draw do
  resources :product_images
  resources :products
  get 'home/about'
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Products/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Products/app/models/product.rb
class Product < ApplicationRecord
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
end

Products/app/models/product_image.rb
class ProductImage < ApplicationRecord
    belongs_to :product
    mount_uploader :iimage, ImagesUploader
end

Products/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Products/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

Products/app/controllers/product_images_controller.rb
class ProductImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @product_images = ProductImage.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @product_image = ProductImage.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @product_image = ProductImage.new(image_params)

    respond_to do |format|
      if @product_image.save
        format.html { redirect_to image_url(@product_image), notice: "ProductImage was successfully created." }
        format.json { render :show, status: :created, location: @product_image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @product_image.update(image_params)
        format.html { redirect_to image_url(@product_image), notice: "ProductImage was successfully updated." }
        format.json { render :show, status: :ok, location: @product_image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @product_image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "ProductImage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @product_image = ProductImage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_image_params
      params.require(:product_image).permit(:image_name, :iimage, :iimage_cache)
    end
end

Products/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:pid, :pcode)
    end
end

Products/app/helpers/application_helper.rb
module ApplicationHelper
end

Products/app/helpers/home_helper.rb
module HomeHelper
end

Products/app/helpers/images_helper.rb
module ImagesHelper
end

Products/app/helpers/products_helper.rb
module ProductsHelper
end

Products/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Products", products_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Readme</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

Products/app/views/home/about.html.erb
<h1> About Us </h1>

Products/app/views/home/index.html.erb
<h1> Product with Images </h1>
<p> Product with Images</p>
<p> Products </p>

Products/app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

Products/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Products</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Products/app/views/product_images/_form.html.erb
<%= form_with(model: @product_image) do |form| %>
  <% if @product_image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@product_image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% @product_image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :image_name, style: "display: block" %>
    <%= form.text_field :image_name %>
  </div>

  <div>
    <%= form.text_field :iimage, label: "Icon" %>
    <%= form.hidden_field :iimage_cache %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Products/app/views/product_images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Iid:</strong>
    <%= image.iid %>
  </p>

  <p>
    <strong>Icode:</strong>
    <%= image.icode %>
  </p>

  <p>
    <strong>Iname:</strong>
    <%= image.iname %>
  </p>

  <p>
    <strong>Iimage:</strong>
    <%= image.iimage %>
  </p>

</div>

Products/app/views/product_images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

Products/app/views/product_images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @product_images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_product_image_path %>

Products/app/views/product_images/new.html.erb
<h1>New image</h1>

<%= render "form"%>

<br>

<div>
  <%= link_to "Back to images", product_images_path %>
</div>

Products/app/views/product_images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>

Products/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pid, style: "display: block" %>
    <%= form.text_field :pid %>
  </div>

  <div>
    <%= form.label :pcode, style: "display: block" %>
    <%= form.text_field :pcode %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Products/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Pid:</strong>
    <%= product.pid %>
  </p>

  <p>
    <strong>Pdesc:</strong>
    <%= product.pcode %>
  </p>

</div>

Products/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

Products/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

Products/app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

Products/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>